name: lsgm
channels:
  - pytorch-lts
  - conda-forge
  - defaults
dependencies:
  - pytorch=1.8.2
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - matplotlib
  - tensorboard
  - tensorboardx
  - scipy
  - pip
  - pip:
    - lmdb
    - tensorflow
    - tfrecord
    - torchdiffeq