name: lsgm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch=1.8.0
  - torchvision=0.9.0
  - torchaudio=0.8.0
  - cudatoolkit=11.1
  - matplotlib
  - tensorboard
  - tensorboardx
  - scipy
  - pip
  - pip:
    - lmdb
    - tensorflow
    - tfrecord
    - torchdiffeq