name: fashion-mnist
channels:
  - conda-forge
  - defaults
dependencies:
  - tensorflow=2.6.0
  - tensorflow-gpu=2.6.0
  - jupyterlab
  - ipywidgets
  - ipykernel
  - iprogress
  - matplotlib
  - pandas
  - pip
  - pip:
    - tensorflow-gan
    - tensorflow-datasets==4.4.0