name: fashion-mnist
channels:
  - conda-forge
  - apple
  - defaults
dependencies:
  - apple::tensorflow-deps=2.7.0
  - jupyterlab
  - ipywidgets
  - ipykernel
  - iprogress
  - matplotlib
  - pip
  - pip:
    - tensorflow-macos==2.7.0
    - tensorflow-metal
    - tensorflow-gan
    - tensorflow-datasets==4.4.0